[package]
name = "cf1062_div4"
version = "0.1.0"
edition = "2021"

[features]
local = []

[dependencies]
ac-library-rs = "=0.1.1"
library = { git="https://github.com/ardRiriy/adry_library.git", rev="402e01b76ed43fda33c45966d0672f7d2fd0ca92" }
