[package]
name = "edpc"
version = "0.1.0"
edition = "2021"

[features]
local = []

[dependencies]
ac-library-rs = "=0.1.1"
library = { git="https://github.com/ardRiriy/adry_library.git", rev="3a135bcdaf5f00f8eefa2de58700b883dc13e68d" }
